Agenda/Agenda.UI/Controllers/AgendaController.cs
using System;
using System.Web.Mvc;
using Agenda.Bll.Services;
using Agenda.Bo;

namespace Agenda.UI.Controllers
{
    public class AgendaController : Controller
    {
        // GET: Agenda
        public ActionResult Index()
        {
            var citasService = new CitasService();

            return View(citasService.GetCitas());
        }

        // GET: Agenda/Details/5
        public ActionResult Details(int id)
        {
            var citasService = new CitasService();
            return View(citasService.GetCita(id));
        }

        // GET: Agenda/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Agenda/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                var citasService = new CitasService();

                var cita = new BoCita
                {
                    Id = 0,
                    Evento = Request.Form["Evento"],
                    Lugar = Request.Form["Lugar"],
                    Fecha = DateTime.Parse(Request.Form["Fecha"])
                };


                if (citasService.CreateOrUpdateCita(cita) > 0)
                {
                    return RedirectToAction("Index");
                }

                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: Agenda/Edit/5
        public ActionResult Edit(int id)
        {
            var citasService = new CitasService();
            return View(citasService.GetCita(id));
        }

        // POST: Agenda/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                var citasService = new CitasService();
                

                var cita = new BoCita
                {
                    Id = id,
                    Evento = Request.Form["Evento"],
                    Lugar = Request.Form["Lugar"],
                    Fecha = DateTime.Parse(Request.Form["Fecha"])
                };


                if (citasService.CreateOrUpdateCita(cita) > 0)
                {
                    return RedirectToAction("Index");
                }

                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: Agenda/Delete/5
        public ActionResult Delete(int id)
        {
            var citasService = new CitasService();
            return View(citasService.GetCita(id));
        }

        // POST: Agenda/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                var citasService = new CitasService();

                if (citasService.DeleteCita(id))
                {
                    return RedirectToAction("Index");
                }

                return View();
            }
            catch
            {
                return View();
            }
        }
    }
}

Agenda/Agenda.UI/Controllers/AgendawaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Agenda.UI.Controllers
{
    public class AgendawaController : Controller
    {
        // GET: Agendawa
        public ActionResult Index()
        {
            return View();
        }
    }
}

Agenda/Agenda.UI/Controllers/CitasController.cs
using System;
using System.Collections.Generic;
using System.Web.Http;
using Agenda.Bll.Services;
using Agenda.Bo;

namespace Agenda.UI.Controllers
{
    public class CitasController : ApiController
    {
        public IEnumerable<BoCita> GetCitas()
        {
            var citasService = new CitasService();
            return citasService.GetCitas();
        }

        public IHttpActionResult GetCita(int id)
        {
            var citasService = new CitasService();
            var cita = citasService.GetCita(id);
            if (cita == null)
            {
                return NotFound();
            }

            return Ok(cita);
        }


        public IHttpActionResult PutCita(int id, BoCita cita)
        {
            if (ModelState.IsValid && id == cita.Id)
            {
                var citasService = new CitasService();
                var result = citasService.CreateOrUpdateCita(cita);

                if (result == 0)
                {
                    return NotFound();
                }

                return Ok(cita);
            }

            return BadRequest(ModelState);
        }

   
        public IHttpActionResult Post(BoCita cita)
        {
            if (ModelState.IsValid)
            {
                var citasService = new CitasService();
                var result = citasService.CreateOrUpdateCita(cita);

                if (result == 0)
                {
                    return NotFound();
                }

                cita.Id = result;
                var uri = new Uri(Url.Link("DefaultApi", new { id = result }));

                return Created(uri, cita);
            }

            return BadRequest(ModelState);
        }

        public IHttpActionResult Delete(int id)
        {
            var citasService =  new CitasService();
            var result = citasService.DeleteCita(id);


            if (!result)
            {
                return NotFound();
            }
            
            return Ok();
        }
    }
}

Agenda/Agenda.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Agenda.Bll.Services;

namespace Agenda.UI.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

    }
}

Agenda/Agenda.UI/Views/Agenda/Create.cshtml
@model Agenda.Bo.BoCita

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BoCita</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Evento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Evento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Evento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lugar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lugar, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lugar, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Agenda/Agenda.UI/Views/Agenda/Delete.cshtml
@model Agenda.Bo.BoCita

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BoCita</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Evento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Evento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lugar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lugar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Agenda/Agenda.UI/Views/Agenda/Details.cshtml
@model Agenda.Bo.BoCita

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>BoCita</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Evento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Evento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lugar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lugar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Agenda/Agenda.UI/Views/Agenda/Edit.cshtml
@model Agenda.Bo.BoCita

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BoCita</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Evento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Evento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Evento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lugar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lugar, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lugar, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @{ Html.EnableClientValidation(false); }
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Fecha, "", new {@class = "text-danger"})
            </div>
            @{ Html.EnableClientValidation(true); }
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Agenda/Agenda.UI/Views/Agenda/Index.cshtml
@model IEnumerable<Agenda.Bo.BoCita>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Evento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lugar)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Evento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Lugar)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Agenda/Agenda.UI/Views/Agendawa/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="container">
    <h2>Citas en la Agenda</h2>    
    
    <button type="button" class="btn btn-primary" 
            data-toggle="modal" 
            data-target="#modalAgenda" 
            onclick="clearTextBox();">Agregar Cita</button>
    <br /><br />
    
    
    <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>No.</th>
            <th>Lugar</th>
            <th>Evento</th>
            <th>Fecha</th>
            <th>#</th>
        </tr>
        </thead>
        <tbody class="tbody">
        
        </tbody>
    </table>
    
    
</div>


<div class="modal fade"
     id="modalAgenda" 
     tabindex="-1" 
     role="dialog"
     aria-labelledby="tituloModalAgenda"
     aria-hidden="true">
    
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h4 class="modal-title" id="tituloModalAgenda">Detalle Cita</h4>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="IdCita">No.</label>
                        <input type="text" class="form-control" id="IdCita" placeholder="Id" disabled="disabled" />
                    </div>
                    <div class="form-group">
                        <label for="Evento">Evento</label>
                        <input type="text" class="form-control" id="Evento" placeholder="Evento" />
                    </div>
                    <div class="form-group">
                        <label for="Lugar">Lugar</label>
                        <input type="text" class="form-control" id="Lugar" placeholder="Lugar" />
                    </div>
                    <div class="form-group">
                        <label for="Fecha">Fecha</label>
                        <input type="text" class="form-control datefield" id="Fecha" placeholder="Fecha" />
                    </div>                    
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" 
                        class="btn btn-primary" 
                        id="btnAdd" 
                        onclick="return agregar();">Agregar</button>
                <button type="button" 
                        class="btn btn-primary" 
                        id="btnUpdate" 
                        style="display:none;" 
                        onclick="actualizar();">Actualizar</button>
                <button type="button" 
                        class="btn btn-default" 
                        data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>     
</div>


@section scripts
{
    @Scripts.Render("~/Scripts/Aplicacion/Agenda.js")
}

Agenda/Agenda.UI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Agenda/Agenda.UI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Agenda/Agenda.UI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Agenda/Agenda.UI/Views/Shared/DisplayTemplates/DateTime.cshtml
@model DateTime?
@(Model != null ? $"{Model:d}" : string.Empty) 

Agenda/Agenda.UI/Views/Shared/EditorTemplates/DateTime.cshtml
@model DateTime?

@{
    DateTime dt = DateTime.Now;
    if (Model != null)
    {
        dt = (System.DateTime)Model;

    }
    @Html.TextBox("", $"{dt.ToShortDateString():d}",
        new { @class = "datefield", type = "string" })
} 

Agenda/Agenda.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")    
   
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Agenda", "Index", "Agendawa")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/jquery-ui.min.js")
    @Scripts.Render("~/Scripts/DatePickerReady.js")
    @Scripts.Render("~/Scripts/moment-with-locales.js")
    @RenderSection("scripts", required: false)
</body>
</html>